// AUTO-GENERATED by scripts/sync-content.mjs — DO NOT EDIT MANUALLY
// Манифест фотографий из папки content/

export const bgImages: string[] = [
  "/images/bg/bg-01.jpg",
  "/images/bg/bg-02.jpg",
  "/images/bg/bg-03.jpg",
  "/images/bg/bg-04.jpg"
]

export const galleryImages: string[] = [
  "/images/okrestnosti/okrestnosti-01.jpg",
  "/images/okrestnosti/okrestnosti-02.jpg",
  "/images/okrestnosti/okrestnosti-03.jpg",
  "/images/okrestnosti/okrestnosti-04.jpeg",
  "/images/okrestnosti/okrestnosti-05.jpg",
  "/images/okrestnosti/okrestnosti-06.jpg",
  "/images/okrestnosti/okrestnosti-07.jpg",
  "/images/okrestnosti/okrestnosti-08.jpg",
  "/images/okrestnosti/okrestnosti-09.jpg",
  "/images/okrestnosti/okrestnosti-10.jpg",
  "/images/okrestnosti/okrestnosti-11.jpg",
  "/images/okrestnosti/okrestnosti-12.jpg",
  "/images/okrestnosti/okrestnosti-13.jpg",
  "/images/okrestnosti/okrestnosti-14.jpg",
  "/images/okrestnosti/okrestnosti-15.jpg",
  "/images/okrestnosti/okrestnosti-16.jpg",
  "/images/okrestnosti/okrestnosti-17.jpg",
  "/images/okrestnosti/okrestnosti-18.jpg",
  "/images/okrestnosti/okrestnosti-19.jpg",
  "/images/okrestnosti/okrestnosti-20.jpg",
  "/images/okrestnosti/okrestnosti-21.jpg",
  "/images/okrestnosti/okrestnosti-22.jpg"
]
