// AUTO-GENERATED by scripts/export-demo.mjs — DO NOT EDIT MANUALLY
// Static demo data for Vercel deployment (no database needed)
// Used when NEXT_PUBLIC_DEMO_MODE=true
// Source: data/guesthouse.db (exported on 2026-08-15 11:37 UTC)

import { Room, Review } from '@/types'

export const demoRooms: Room[] = [
  {
    "id": "cmpeklys5xdbvbqmf",
    "name": "{\"ru\":\"ROOM Micheli's Guest House\",\"az\":\"ROOM Micheli's Guest House\",\"en\":\"ROOM Micheli's Guest House\"}",
    "description": "{\"ru\":\"Просторный дом для отдыха в Ивановке с приватной территорией, бассейном и полной инфраструктурой для комфортного проживания.\\nИдеально подходит для семей, компаний друзей и спокойных выходных на природе.\",\"az\":\"\",\"en\":\"\"}",
    "conditions": "{\"ru\":\"• Заезд: 14:00\\n• Выезд: 13:00\\n• Курение в доме запрещено\",\"az\":\"\",\"en\":\"\"}",
    "advantages": {
      "ru": [
        "2 спальни",
        "Гостиная зона",
        "Полностью оборудованная кухня",
        "Обеденная зона",
        "Собственный бассейн",
        "Терраса и сад"
      ],
      "az": [],
      "en": []
    },
    "price": 150,
    "capacity": 4,
    "amenities": {
      "ru": [
        "Бесплатный Wi-Fi",
        "Частная парковка",
        "Открытый бассейн",
        "BBQ зона",
        "Завтрак",
        "Настольные Игры",
        "Размещение с животными"
      ],
      "az": [],
      "en": []
    },
    "images": [
      "/images/micheli/micheli-01.jpg",
      "/images/micheli/micheli-18.jpeg",
      "/images/micheli/micheli-04.jpg",
      "/images/micheli/micheli-05.jpg",
      "/images/micheli/micheli-10.jpg",
      "/images/micheli/micheli-07.jpg",
      "/images/micheli/micheli-06.jpg",
      "/images/micheli/micheli-22.jpeg",
      "/images/micheli/micheli-11.jpeg",
      "/images/micheli/micheli-12.jpeg",
      "/images/micheli/micheli-15.jpeg",
      "/images/micheli/micheli-09.jpg",
      "/images/micheli/micheli-08.jpg",
      "/images/micheli/micheli-14.jpeg",
      "/images/micheli/micheli-13.jpeg",
      "/images/micheli/micheli-17.jpeg",
      "/images/micheli/micheli-16.jpeg",
      "/uploads/1786705112176-pc9tbk.jpg",
      "/images/micheli/micheli-23.jpeg",
      "/images/micheli/micheli-24.jpeg",
      "/images/micheli/micheli-20.jpeg",
      "/images/micheli/micheli-03.jpg",
      "/images/micheli/micheli-21.jpeg",
      "/images/micheli/micheli-02.jpg",
      "/images/micheli/micheli-19.jpeg"
    ],
    "bookingUrl": "https://www.booking.com/hotel/az/michelis-guest-house.ru.html",
    "isAvailable": true
  },
  {
    "id": "cmpfdyx9j4b1178by",
    "name": "{\"ru\":\"ROOM Miran’s Guest House\",\"az\":\"\",\"en\":\"\"}",
    "description": "{\"ru\":\"Уютный загородный дом в Ивановке с атмосферой спокойствия, приватности и полного отдыха на природе.\\nПодходит для семейного отдыха и небольших компаний\",\"az\":\"\",\"en\":\"\"}",
    "conditions": "{\"ru\":\"• Заезд: 14:00\\n• Выезд: 13:00\\n• Курение в доме запрещено\",\"az\":\"\",\"en\":\"\"}",
    "advantages": {
      "ru": [
        "2 спальни",
        "Гостиная",
        "Кухня",
        "Терраса",
        "Сад"
      ],
      "az": [],
      "en": []
    },
    "price": 150,
    "capacity": 4,
    "amenities": {
      "ru": [
        "Бесплатный Wi-Fi",
        "Бесплатная парковка",
        "BBQ зона",
        "Завтрак",
        "Настольные Игры",
        "Размещение с животными",
        "Сауна (доп. оплата)"
      ],
      "az": [],
      "en": []
    },
    "images": [
      "/images/miran/miran-15.jpeg",
      "/images/miran/miran-13.jpeg",
      "/images/miran/miran-16.jpeg",
      "/images/miran/miran-09.jpeg",
      "/images/miran/miran-04.jpeg",
      "/images/miran/miran-03.jpeg",
      "/images/miran/miran-06.jpeg",
      "/images/miran/miran-05.jpeg",
      "/images/miran/miran-02.jpeg",
      "/images/miran/miran-14.jpeg",
      "/images/miran/miran-07.jpeg",
      "/images/miran/miran-20.jpg",
      "/images/miran/miran-08.jpeg",
      "/images/miran/miran-01.jpeg",
      "/images/miran/miran-22.jpg",
      "/images/miran/miran-11.jpeg",
      "/images/miran/miran-23.jpg",
      "/images/miran/miran-12.jpeg",
      "/images/miran/miran-10.jpeg",
      "/images/miran/miran-17.jpeg",
      "/images/miran/miran-18.jpeg",
      "/images/miran/miran-19.jpeg",
      "/images/miran/miran-24.jpg"
    ],
    "bookingUrl": "https://www.booking.com/hotel/az/room-mirans-guest-house-ivanovka.ru.html",
    "isAvailable": true
  }
]

export const demoReviews: Review[] = [
  {
    "id": "cmsuaim6w6g3gj7s3",
    "guestName": "Mahammad",
    "rating": 5,
    "comment": "Все было очень чисто и аккуратно 10/10",
    "isApproved": true,
    "createdAt": "2026-08-15 11:26:05"
  },
  {
    "id": "cmpejpncjhhhsg4oo",
    "guestName": "Yekaterina",
    "rating": 5,
    "comment": "We had a wonderful stay! The house is very clean, cozy, and has a charming countryside atmosphere. It is equipped with absolutely everything you might need for a comfortable stay, so we didn't miss a thing.",
    "isApproved": true,
    "createdAt": "2026-05-20 21:00:04"
  },
  {
    "id": "cmpejpmusp7e9c4y4",
    "guestName": "Sara",
    "rating": 5,
    "comment": "Понравилось все! Интерьер с натуральным деревом, аккуратные изюминки делающие пребывание всё более теплым и уютным. Завтрак был свежим, вкусным, чистым, аккуратное, натуральное! Хозяин всегда был на связи по всем вопросам. Помогал разобраться при надобности (независимо от часа дня). Мы провели очень веселые, приятные выходные с самоварным чаем и рыбой на мангале своими руками, под свою музыку из-под колонок. Спасибо за все! 🙏🏻",
    "isApproved": true,
    "createdAt": "2026-05-20 21:00:03"
  },
  {
    "id": "cmpejphnpoxci6le5",
    "guestName": "Ranga",
    "rating": 5,
    "comment": "Very good location and design",
    "isApproved": true,
    "createdAt": "2026-05-20 20:59:56"
  }
]

export const demoSettings = {
  "phone": "+994508080069",
  "email": "roomcommunityofficial@gmail.com",
  "address": "Азербайджан, г. Исмаиллы, посёлок Ивановка",
  "description": "Уютные гостевые дома в горах Азербайджана. Отдых в окружении величественных гор и густых лесов."
}
