// Экспорт данных из SQLite (data/guesthouse.db) в src/lib/demo-data.ts
// для демо-режима на Vercel (NEXT_PUBLIC_DEMO_MODE=true).
//
// Запуск: npm run export-demo
// Запускать после правок контента через админку, затем закоммитить результат.

import Database from 'better-sqlite3'
import { writeFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const dbPath = path.join(root, 'data', 'guesthouse.db')
const outPath = path.join(root, 'src', 'lib', 'demo-data.ts')

function parseJson(value, fallback) {
  if (value === undefined || value === null) return fallback
  if (typeof value !== 'string') return value
  try {
    return JSON.parse(value)
  } catch {
    return fallback
  }
}

const db = new Database(dbPath, { readonly: true })

const rooms = db.prepare('SELECT * FROM Room WHERE isAvailable = 1 ORDER BY createdAt ASC').all()
const reviews = db.prepare('SELECT * FROM Review WHERE isApproved = 1 ORDER BY createdAt DESC LIMIT 5').all()
const settings = db.prepare('SELECT * FROM SiteSettings LIMIT 1').get()
db.close()

const demoRooms = rooms.map((row) => ({
  id: row.id,
  name: row.name, // localized JSON-строка — как в БД
  description: row.description,
  conditions: row.conditions,
  advantages: parseJson(row.advantages, []),
  price: row.price,
  capacity: row.capacity,
  amenities: parseJson(row.amenities, []),
  images: parseJson(row.images, []),
  bookingUrl: row.bookingUrl || '',
  isAvailable: Boolean(row.isAvailable),
}))

const demoReviews = reviews.map((row) => ({
  id: row.id,
  guestName: row.guestName,
  rating: row.rating,
  comment: row.comment,
  createdAt: row.createdAt,
}))

const demoSettings = settings
  ? {
      phone: settings.phone,
      email: settings.email || '',
      address: settings.address || '',
      description: settings.description || '',
    }
  : {
      phone: '+994508080069',
      email: 'roomcommunityofficial@gmail.com',
      address: 'Азербайджан, г. Исмаиллы, посёлок Ивановка',
      description: 'Уютные гостевые дома в горах Азербайджана. Отдых в окружении величественных гор и густых лесов.',
    }

const now = new Date()
const stamp = now.toISOString().slice(0, 16).replace('T', ' ')

const content = `// AUTO-GENERATED by scripts/export-demo.mjs — DO NOT EDIT MANUALLY
// Static demo data for Vercel deployment (no database needed)
// Used when NEXT_PUBLIC_DEMO_MODE=true
// Source: data/guesthouse.db (exported on ${stamp} UTC)

import { Room, Review } from '@/types'

export const demoRooms: Room[] = ${JSON.stringify(demoRooms, null, 2)}

export const demoReviews: Review[] = ${JSON.stringify(demoReviews, null, 2)}

export const demoSettings = ${JSON.stringify(demoSettings, null, 2)}
`

writeFileSync(outPath, content, 'utf8')

console.log(`✅ demo-data.ts обновлён: ${demoRooms.length} домов, ${demoReviews.length} отзывов`)
