// Синхронизация фото из content/ в public/images/ + обновление images домов в БД
// + генерация src/lib/content-manifest.ts
//
// Запуск: npm run sync-content (затем npm run export-demo для демки)
// content/ — локальная папка-источник (в .gitignore), в репо уходят только копии в public/

import Database from 'better-sqlite3'
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const IMAGE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp'])

const jobs = [
  { src: 'content/bckgrnd', dest: 'public/images/bg', prefix: 'bg' },
  { src: 'content/Micheli`s', dest: 'public/images/micheli', prefix: 'micheli' },
  { src: 'content/Miran`s', dest: 'public/images/miran', prefix: 'miran' },
  { src: 'content/Okrestnosti', dest: 'public/images/okrestnosti', prefix: 'okrestnosti' },
]

const naturalSort = (a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' })

const manifest = {}

for (const job of jobs) {
  const srcDir = path.join(root, job.src)
  const destDir = path.join(root, job.dest)

  if (!existsSync(srcDir)) {
    console.warn(`⚠️  ${job.src}: папка не найдена, пропуск`)
    continue
  }

  const files = readdirSync(srcDir)
    .filter((f) => IMAGE_EXT.has(path.extname(f).toLowerCase()))
    .sort(naturalSort)

  if (files.length === 0) {
    console.warn(`⚠️  ${job.src}: фото не найдены, пропуск`)
    continue
  }

  // Чистим целевую папку от старых синхронизированных файлов
  rmSync(destDir, { recursive: true, force: true })
  mkdirSync(destDir, { recursive: true })

  const paths = []
  files.forEach((file, i) => {
    const ext = path.extname(file).toLowerCase()
    const name = `${job.prefix}-${String(i + 1).padStart(2, '0')}${ext}`
    copyFileSync(path.join(srcDir, file), path.join(destDir, name))
    paths.push(`/images/${job.prefix}/${name}`)
  })

  manifest[job.prefix] = paths
  console.log(`✓ ${job.prefix}: ${files.length} фото`)
}

// Обновляем images домов в БД (матч по имени)
const db = new Database(path.join(root, 'data', 'guesthouse.db'))
const rooms = db.prepare('SELECT id, name FROM Room').all()
for (const room of rooms) {
  const key = room.name.includes('Micheli') ? 'micheli' : room.name.includes('Miran') ? 'miran' : null
  if (!key || !manifest[key]) continue
  db.prepare("UPDATE Room SET images = ?, updatedAt = datetime('now') WHERE id = ?").run(
    JSON.stringify(manifest[key]),
    room.id
  )
  console.log(`✓ Room ${room.id} -> ${manifest[key].length} фото`)
}
db.close()

// Генерируем манифест для фона и галереи
const content = `// AUTO-GENERATED by scripts/sync-content.mjs — DO NOT EDIT MANUALLY
// Манифест фотографий из папки content/

export const bgImages: string[] = ${JSON.stringify(manifest.bg ?? [], null, 2)}

export const galleryImages: string[] = ${JSON.stringify(manifest.okrestnosti ?? [], null, 2)}
`
writeFileSync(path.join(root, 'src', 'lib', 'content-manifest.ts'), content, 'utf8')
console.log('✓ content-manifest.ts сгенерирован')
console.log('DONE')
